#!/usr/bin/python

class Symbol:
	def __init__(self):
		self.filename = ""
	def set_filename(self,filename):
		self.filename = filename
	def process_file(self):
		f = open(self.filename)
		text = f.read().strip()
		for i,j in enumerate(text.split('\n')):
			shs,eng = j.split(';')
			print shs,eng
#			print_entry(i,shs,eng)


#def print_entry(id,shs,eng):
#	print "<d:entry id=\""+str(id)+"\" d:title=\""+shs+"\" d:parental-control=\"1\">"
#	print "<d:index d:value=\""+shs+"\"/>"
#        print "<h1>"+shs+"</h1>"
#        print "<ul>"
#        print "<li>"+eng+" </li>"
#        print "</ul>"
#	print "</d:entry>"
#

filename = "EnglishSecwepemcDictionary.txt"
#
#
handler = Symbol()
handler.set_filename(filename)
print handler.filename
handler.process_file()
